config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets, only: nil do
    resources :tweet_reviews, only: :new
  end

  resources :tweet_reviews, only: [:new, :edit, :create, :update]

  get '/aotm', to: 'aotm#index', as: :aotm

  get '/reviewers/:screen_name/feed', to: 'reviewer_feed_items#index', as: :reviewer

  get '/ratings/:rating/reviews', to: 'reviews#index', as: :ratings

  get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  get '/profile', to: 'reviewer_feed_items#index'
  get '/settings', to: 'users#edit'

  resources :users, only: :update

  resources :albums, only: :index

  root 'feed_items#index'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :in_reply_to_tweet, class_name: 'Tweet', required: false
  has_one :reply, foreign_key: :in_reply_to_tweet_id, class_name: 'Tweet'
  has_one :tweet_review

  validates :tweet_id, uniqueness: true

  default_scope -> { order(tweeted_at: :desc) }

  def reply?
    in_reply_to_tweet_id.present?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def remove_hashtag_and_rating(tweet_text)
    tweet_text
      .strip
      .gsub(/(\d\s*[+|-]?\s*)?#julysoundcheck$/i, '')
      .gsub(/(\d\s*[+|-]?)$/, '')
      .strip
  end

  def can_edit?(tweet)
    return true if is_admin_user?
    if twitter_user
      tweet.screen_name == twitter_user.screen_name
    elsif current_user
      tweet.user.id == current_user.id
    else
      false
    end
  end

  def is_admin_user?
    if twitter_user
      is_admin_screen_name?(twitter_user.screen_name)
    elsif current_user
      is_admin_email?(current_user.email)
    end
  end

  def link_recommender(tweet_text)
    tweet_text.gsub(/@\w+/) do |screen_name|
      link_to(screen_name,
              reviewer_path(screen_name.delete('@')),
              class: 'recommender')
    end
  end

  def recent_tweets
    return [] unless current_user
    Tweet
      .where(user: current_user, in_reply_to_tweet_id: nil)
      .includes(:reply)
      .limit(3)
      .map do |tweet|
        JulySoundcheckTweet.new(tweet)
      end
  end

  private

  def is_admin_screen_name?(screen_name)
    screen_name == ENV['ADMIN_TWITTER_SCREEN_NAME'] ||
      screen_name == ENV['TEST_ADMIN_TWITTER_SCREEN_NAME']
  end

  def is_admin_email?(email)
    email == ENV['ADMIN_EMAIL'] || email == ENV['TEST_ADMIN_EMAIL']
  end
end

app/views/tweets/_tweet.html.erb
<div class="tweet-review row">
  <div class="large-1 medium-2 small-2 columns">
    <img class='twitter-profile-image' align="left" src="<%= tweet.profile_image_uri %>" />
  </div>
  <div class="large-11 medium-10 small-10 columns">
    <div class="tweet-title row">
      <div class="large-10 columns">
        <div class='twitter-name'><%= tweet.user_name %></div>
        <div class='twitter-username'>
          <%= link_to "@#{tweet.screen_name}", reviewer_path(tweet.screen_name) %>
        </div>
      </div>
      <div class="reviewed-on">
        <%= tweet.tweeted_on.to_formatted_s(:long_ordinal) %>
      </div>
    </div>
    <div class="row">
      <div class="review large-12 columns">
        <div class="review-text-container <%= 'no-embed' unless tweet.listen_source %>">
          <% if tweet.two_part? %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet.text)).html_safe %>
            </p>
            <% if tweet.rating %>
              <div class='review-rating' title="<%= tweet.rating.description %>">
                <%= tweet.rating %>
              </div>
            <% end %>
            <p class="tweet-reply">
              <%= link_recommender(remove_hashtag_and_rating(tweet.review_text)).html_safe %>
            </p>
          <% else %>
          <% if tweet.rating %>
            <div class='review-rating' title="<%= tweet.rating.description %>">
              <%= tweet.rating %>
            </div>
          <% end %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet.text)).html_safe %>
            </p>
          <% end %>
        </div>
      </div>
    </div>

    <% if tweet.genre %>
      <div class="row genre">
        <div class="large-12 columns">
          <em><%= tweet.genre %></em>
        </div>
      </div>
    <% end %>

    <% if tweet.listen_source %>
      <div class="row listen-embed">
        <div class="large-12 columns">
          <%= render partial: "tweets/#{tweet.listen_source.source}", locals: {tweet: tweet} %>
        </div>
      </div>
    <% end %>
    <% if can_edit?(tweet) %>
      <div class="row">
        <div class="large-12 columns">
          <% if tweet.review_details? %>
            <%= link_to 'Edit review details', edit_tweet_review_path(tweet.tweet_review) %>
          <% else %>
            <%= link_to 'Add review details', new_tweet_tweet_review_path(tweet.id) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div  class="row">
  <div id="page_title" class="large-9 medium-8 small-8 columns">
    <% if params[:rating] %>
      <h2>
        <%= rating_group_description(params[:rating]) %>
      </h2>
    <% else %>
      <h2>All Tweets</h2>
    <% end %>
  </div>
  <div  id="ratings_filter" class="columns large-3 medium-4 small-4">
    <ul class="dropdown menu float-right" data-dropdown-menu>
      <li>
        <a class="small button float-right" href="javascript:;">Filter</a>
        <ul class="menu">
          <li><%= link_to 'None', tweets_path %></li>
          <%= rating_group_links %>
        </ul>
      </li>
    </ul>
  </div>
</div>

<% @jsc_tweets.each do |tweet| %>
  <%= render partial: 'tweet', locals: {tweet: tweet} %>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= paginate @tweets %>
  </div>
</div>