config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets, only: nil do
    resources :tweet_reviews, only: :new
  end

  resources :tweet_reviews, only: [:new, :edit, :create, :update]

  get '/aotm', to: 'aotm#index', as: :aotm

  get '/reviewers/:screen_name/feed', to: 'reviewer_feed_items#index', as: :reviewer

  get '/ratings/:rating/reviews', to: 'reviews#index', as: :ratings

  get '/auth/twitter/callback', to: 'sessions#create', as: 'callback'
  delete '/signout', to: 'sessions#destroy', as: 'signout'

  get '/profile', to: 'reviewer_feed_items#index'
  get '/settings', to: 'users#edit'

  resources :users, only: :update

  resources :albums, only: :index

  root 'feed_items#index'
end

app/models/feed_item.rb
class FeedItem < ApplicationRecord
  belongs_to :feedable, polymorphic: true
  belongs_to :user

  validates :feedable_id, uniqueness: { scope: :feedable_type }
end

app/controllers/feed_items_controller.rb
require './lib/error_logger'

class FeedItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :create_new_feed_items, only: :index
  before_action :set_feed_items, only: :index

  private

  def set_feed_items
    @feed_items =
      FeedItem
      .includes(:feedable)
      .order(created_at: :desc)
      .page(params[:page])
  end

  def create_new_feed_items
    # Rails.cache.fetch 'tweet-archiver', expires_in: 5.minutes do
    #   Archiver::TweetArchiver.archive
    # end
  rescue Exception => exception
    ErrorLogger.log(exception)
  end
end

app/helpers/feed_items_helper.rb
module FeedItemsHelper
  def feed_item_partial(feed_item)
    "/feed_items/#{feedable_type(feed_item).underscore}_item"
  end

  def feed_item_locals(feed_item)
    presenter = july_soundcheck_presenter_for(feed_item)
    { feedable_type(feed_item).underscore.to_sym => presenter.new(feed_item.feedable, feed_item) }
  end

  private

  def feedable_type(feed_item)
    type = feed_item.feedable_type
    type = 'Review' if type == 'TweetReview' && feed_item.feedable.tweet.nil?
    type
  end

  def july_soundcheck_presenter_for(feed_item)
    type = feedable_type(feed_item)
    if type == 'Tweet'
      JulySoundcheckTweet
    elsif type == 'Review'
      JulySoundcheckReview
    else
      JulySoundcheckTweetReview
    end
  end
end

app/views/feed_items/_filter.html.erb
<div id="ratings_filter" class="columns large-3 medium-4 small-4">
  <ul class="dropdown menu float-right" data-dropdown-menu>
    <li>
      <a class="small button float-right" href="javascript:;">Filter</a>
      <ul class="menu">
        <li><%= link_to 'None', root_path %></li>
        <li><%= link_to 'AOTM', aotm_path %></li>
        <%= rating_group_links %>
      </ul>
    </li>
  </ul>
</div>

app/views/feed_items/_rating_badge.html.erb
<% if tweet_review.album_of_the_month? %>
  <a href="/aotm" class='album-of-the-month' title="Album Of The Month - <%= tweet_review.rating %>">
    <span>A</span>
    <span>O</span>
    <span>T</span>
    <span>M</span>
  </a>
<% else %>
  <a class='review-rating' title="<%= tweet_review.rating_description %>">
    <%= tweet_review.rating %>
  </a>
<% end %>

app/views/feed_items/_review_item.html.erb
<div id="review_<%= review.id %>" class="tweet-review review-item row">
  <div class="large-1 medium-2 small-2 columns">
    <%= link_to reviewer_path(review.user) do %>
      <% if review.twitter_account? && !review.profile_image_uri.blank? %>
        <img class='user-profile-image' src="<%= review.profile_image_uri %>" />
      <% else %>
        <%= image_tag 'logo-medium.png', align: 'left', class: 'user-profile-image' %>
      <% end %>
    <% end %>
  </div>
  <div class="large-11 medium-10 small-10 columns">
    <div class="tweet-title row">
      <div class="large-10 columns">
        <div class='user-name'>
          <%= link_to review.user_name, reviewer_path(review.user) %>
        </div>
        <% if review.twitter_account? %>
          <div class='twitter-username'>
            <%= link_to "@#{review.screen_name}", reviewer_path(review.user) %>
          </div>
        <% end %>
      </div>
      <div class="reviewed-on">
        <%= review.reviewed_on.to_formatted_s(:long_ordinal) %>
      </div>
    </div>
    <div class="row">
      <div class="review large-12 columns">
        <div class="review-text-container <%= 'no-embed' unless review.listen_source %>">
          <% if review.rating %>
            <%= render partial: 'feed_items/rating_badge', locals: {tweet_review: review} %>
          <% end %>
          <p class="tweet-text">
            <%= link_recommender(review.text.to_s).html_safe %>
          </p>
        </div>
      </div>
    </div>

    <% if review.listen_source %>
      <% if review.genre %>
        <div class="row genre">
          <div class="large-12 columns">
            <em><%= review.genre %></em>
          </div>
        </div>
      <% end %>

        <div class="row listen-embed">
          <div class="large-12 columns">
            <%= render partial: "/feed_items/embeds/#{review.listen_source.source}", locals: {review: review} %>
          </div>
        </div>
    <% else %>
      <div class="row genre">
        <div class="large-12 columns">
          <strong><%= review.artist %></strong>
          &mdash;
          <span>"<%= review.album %>"</span>
          &mdash;
          <em><%= review.genre %></em>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/feed_items/_tweet_item.html.erb
<div id="tweet_<%= tweet.id %>" class="tweet-review tweet-item row">
  <div class="large-1 medium-2 small-2 columns">
    <%= link_to reviewer_path(tweet.user) do %>
      <% unless tweet.profile_image_uri.blank? %>
        <img class='user-profile-image' src="<%= tweet.profile_image_uri %>" />
      <% else %>
        <%= image_tag 'logo-medium.png', align: 'left', class: 'user-profile-image' %>
      <% end %>
    <% end %>
  </div>
  <div class="large-11 medium-10 small-10 columns">
    <div class="tweet-title row">
      <div class="large-10 columns">
        <div class='user-name'>
          <%= link_to tweet.user_name, reviewer_path(tweet.user) %>
        </div>
        <div class='twitter-username'>
          <%= link_to "@#{tweet.screen_name}", reviewer_path(tweet.user) %>
        </div>
      </div>
      <div class="reviewed-on">
        <%= tweet.tweeted_on.to_formatted_s(:long_ordinal) %>
      </div>
    </div>
    <div class="row">
      <div class="review large-12 columns">
        <div class="review-text-container no-embed">
          <% if tweet.two_part? %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet.text)).html_safe %>
            </p>
            <% if tweet.rating %>
              <div class='review-rating' title="<%= tweet.rating.description %>">
                <%= tweet.rating %>
              </div>
            <% end %>
            <p class="tweet-reply">
              <%= link_recommender(remove_hashtag_and_rating(tweet.review_text)).html_safe %>
            </p>
          <% else %>
          <% if tweet.rating %>
            <div class='review-rating' title="<%= tweet.rating.description %>">
              <%= tweet.rating %>
            </div>
          <% end %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet.text)).html_safe %>
            </p>
          <% end %>
        </div>
      </div>
    </div>

    <% if can_edit?(tweet) %>
      <div class="row">
        <div class="large-12 columns">
          <%= link_to 'Add review details', new_tweet_tweet_review_path(tweet.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/feed_items/_tweet_review_item.html.erb
<div id="tweet_review_<%= tweet_review.id %>" class="tweet-review tweet-review-item row">
  <div class="large-1 medium-2 small-2 columns">
    <%= link_to reviewer_path(tweet_review.user) do %>
      <% unless tweet_review.profile_image_uri.blank? %>
        <img class='user-profile-image' src="<%= tweet_review.profile_image_uri  %>" />
      <% else %>
        <%= image_tag 'logo-medium.png', align: 'left', class: 'user-profile-image' %>
      <% end %>
    <% end %>
  </div>
  <div class="large-11 medium-10 small-10 columns">
    <div class="tweet-title row">
      <div class="large-10 columns">
        <div class='user-name'>
          <%= link_to tweet_review.user_name, reviewer_path(tweet_review.user) %>
        </div>
        <div class='twitter-username'>
          <%= link_to "@#{tweet_review.screen_name}", reviewer_path(tweet_review.user) %>
        </div>
      </div>
      <div class="reviewed-on">
        <%= tweet_review.reviewed_on.to_formatted_s(:long_ordinal) %>
      </div>
    </div>
    <div class="row">
      <div class="review large-12 columns">
        <div class="review-text-container <%= 'no-embed' unless tweet_review.listen_source %>">
          <% if tweet_review.two_part? %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet_review.text)).html_safe %>
            </p>
            <% if tweet_review.rating %>
              <%= render partial: 'feed_items/rating_badge', locals: {tweet_review: tweet_review} %>
            <% end %>
            <p class="tweet-reply">
              <%= link_recommender(remove_hashtag_and_rating(tweet_review.review_text)).html_safe %>
            </p>
          <% else %>
          <% if tweet_review.rating %>
            <%= render partial: 'feed_items/rating_badge', locals: {tweet_review: tweet_review} %>
          <% end %>
            <p class="tweet-text">
              <%= link_recommender(remove_hashtag_and_rating(tweet_review.text)).html_safe %>
            </p>
          <% end %>
        </div>
      </div>
    </div>

    <% if tweet_review.listen_source %>
      <% if tweet_review.genre %>
        <div class="row genre">
          <div class="large-12 columns">
            <em><%= tweet_review.genre %></em>
          </div>
        </div>
      <% end %>

        <div class="row listen-embed">
          <div class="large-12 columns">
            <%= render partial: "/feed_items/embeds/#{tweet_review.listen_source.source}", locals: {review: tweet_review} %>
          </div>
        </div>
    <% else %>
      <div class="row genre">
        <div class="large-12 columns">
          <strong><%= tweet_review.artist %></strong>
          &mdash;
          <span>"<%= tweet_review.album %>"</span>
          &mdash;
          <em><%= tweet_review.genre %></em>
        </div>
      </div>
    <% end %>

    <% if can_edit?(tweet_review) %>
      <div class="row">
        <div class="large-12 columns">
          <%= link_to 'Edit review details', edit_tweet_review_path(tweet_review.tweet_review) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/feed_items/index.html.erb
<div class="row">
  <div id="page_title" class="large-9 medium-8 small-8 columns">
    <% if params[:rating] %>
      <h2>
        <%= rating_group_description(params[:rating]) %>
      </h2>
    <% end %>
  </div>
  <%= render partial: 'feed_items/filter' %>
</div>

<% @feed_items.each do |feed_item| %>
  <%= render partial: feed_item_partial(feed_item), locals: feed_item_locals(feed_item) %>
<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= paginate @feed_items %>
  </div>
</div>

<% if @feed_items.empty? %>
  <div id="no_reviews" class="row">
    <div class="large-12 columns">
      <em>No #JulySoundcheck Reviews</em>
    </div>
  </div>
<% end %>

<% content_for :sidebar do %>
  <% if signed_in? %>
    <% #= render partial: 'layouts/recent-tweets' %>
  <% else %>
    <% #= render partial: 'layouts/twitter-sign-in' %>
  <% end %>
<% end %>